# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets',
                'verbose_name': '\u8d44\u4ea7',
                'verbose_name_plural': '\u8d44\u4ea7',
            },
        ),
        migrations.CreateModel(
            name='dbBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('curdate', models.DateField(auto_now=True, verbose_name='\u6700\u65b0\u5907\u4efd\u65e5\u671f')),
                ('inc', models.CharField(max_length=8, verbose_name='\u6700\u65b0\u5907\u4efd\u65f6\u95f4')),
                ('backup_type', models.SmallIntegerField(choices=[(0, '\u5b8c\u6574\u5907\u4efd'), (1, '\u589e\u91cf\u5907\u4efd')], verbose_name='\u5907\u4efd\u7c7b\u578b')),
            ],
            options={
                'db_table': 'dbBackupMonitor',
                'verbose_name': 'DB\u5907\u4efd',
                'verbose_name_plural': 'DB\u5907\u4efd',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200, verbose_name='\u9879\u76ee\u6807\u8bc6')),
                ('game_cn', models.CharField(max_length=200, verbose_name='\u9879\u76ee\u4e2d\u6587\u7b80\u79f0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.AddField(
            model_name='dbbackup',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='god.Game', verbose_name='\u9879\u76ee\u6807\u8bc6'),
        ),
        migrations.AddField(
            model_name='assets',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='god.Game', verbose_name='\u9879\u76ee\u6807\u8bc6'),
        ),
    ]
