# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('god', '0002_auto_20170224_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': '\u9879\u76ee', 'verbose_name_plural': '\u9879\u76ee'},
        ),
    ]
