# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:22
from __future__ import unicode_literals

from django.db import migrations
import god.custom.myfield


class Migration(migrations.Migration):

    dependencies = [
        ('god', '0003_auto_20170224_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_list',
            field=god.custom.myfield.ListField(default=''),
        ),
    ]
