# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('god', '0007_auto_20170304_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='datetime',
            field=models.CharField(max_length=60, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='dbbackup',
            name='curdate',
            field=models.CharField(max_length=60, verbose_name='\u6700\u65b0\u5907\u4efd\u65e5\u671f'),
        ),
    ]
